### ISSUE TITLE
Land directly into the docs

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-old#1]
Right now it lands to http://docs.cosmwasm.com/ index page which contains sections like pictures and who uses. If you want this link directly into the docs(http://docs.cosmwasm.com/docs/intro/overview) take a look at this commit https://github.com/iov-one/docs/commit/c5497e39e244250845a19d6456896fe52c1bae4d.
you can make `window.location.href = 'docs/intro/overview.html';` to land directly to the docs.

**Comment by ethanfrey** [comment]
Actually, I like the landing page. I need to flesh it out more though
