### ISSUE TITLE
Upgrade tutorial to cosmwasm 0.7

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/docs-old#22]
When cosmwasm 0.7 is release, this will mean a number of changes to contract development. There is also a new `escrow` contract release to start with as a basis. We should update the tutorial to match it.

This requires not only a tagged 0.7 `cosmwasm` for contract development, but a tagged `wasmd` that supports 0.7 contracts.

**Comment by clevinson** [comment]
@ethanfrey Is the current master branch of the `escrow` contract ready and cosmwasm 0.7 compatible? I'm happy to start work on upgrading tutorials once 0.7 is ready.

Sidenote: currently the `wasmd version` subcommand does not work. I've filed a seperate issue for that (https://github.com/cosmwasm/wasmd/issues/24)

**Comment by ethanfrey** [comment]
@clevinson I decided to cut a stable toolchain (cosmwasm + wasmd) with cosmwasm0.6 support, as I heard cosmos-sdk 0.38 is almost out, and we can get a stable state asap. (And testnet).

`escrow` and `erc20` are both at 0.6.1, wasmd is not, so the blockchain part won't work.
This should probably wait until we have 0.6 support in wasmd... hopefully later this week.

**Comment by tac0turtle** [comment]
this is blocked on sdk 0.38.1 correct?

**Comment by ethanfrey** [comment]
No. The tutorial was updated to 0.6 (but can use a review and maybe polish). 0.6 will be released with 0.38.1 but no api changes.

0.7 is in progress with api changes. This task is for the future

**Comment by ethanfrey** [comment]
I'm going through this now

**Comment by ethanfrey** [comment]
Closed by #36
